### ISSUE TITLE
"npm install" fails

### ISSUE THREAD

**Issue by numiri** [OpenBCI/OpenBCI_Hub#14]
[npm-install-openbci-ganglion.txt](https://github.com/OpenBCI/OpenBCI_Ganglion_Electron/files/1040331/npm-install-openbci-ganglion.txt)

I followed your installation instructions and 
"npm install" complains about a missing file
    OpenBCI_Ganglion_Electron/node_modules/electron/install.js
the directory OpenBCI_Ganglion_Electron/node_modules/electron does not exist at all in the git download, so I did the following:

> npm install -g electron
> npm start       (result is error:  cannot find module openbci-ganglion)
> npm install -g openbci-ganglion    (more errors.  I attached the error file in this issue, but here's the gist)

node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v51-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@7.9.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.9.0"
(not really a permission issue.  /root/.node-gyp does not exist)

I am installing on raspberry pi model 3b, running raspbian 4.4.34
I'd appreciate any insight you can offer.
Thank you,
Sebastian

**Comment by aj-ptw** [comment]
Electron as far as I know does not run on raspberry pi, therefore you should be trying to try and adapt to [OpenBCI_NodeJS_Ganglion](https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion).

What is your end goal here? To run a web server and use BLE on the rasp pi to to read and parse the binary byte stream coming in?

AJ

**Comment by aj-ptw** [comment]
Electron as far as I know does not run on raspberry pi, therefore you should be trying to try and adapt to [OpenBCI_NodeJS_Ganglion](https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion).

What is your end goal here? To run a web server and use BLE on the rasp pi to to read and parse the binary byte stream coming in?

**Comment by numiri** [comment]
Thanks AJ.  My end goal is to get the OpenBCI GUI running on Raspberry Pi because it's an affordable wearable computer.  I just don't think that people should have to shell out a bunch of money for Windows OS or Mac hardware.  Besides, I had trouble w/ the ftdi driver on Windows 10.

Although javascript is my language of choice and I appreciate the OpenBCI_NodeJS_Ganglion API,  I just thought it'd be lovely to have a little instant gratification w/ the openbci gui.

**Comment by aj-ptw** [comment]
@numiri 

Run in power shell:
1. `npm install --global --production windows-build-tools` in power shell. Verify you have Python 2.7.13 installed to Program files. Verify you can run python from powershell. Make sure it's on your path by running powershell as admin and entering ` [Environment]::SetEnvironmentVariable("Path", "$env:Path;C:\Python27", "User")` into the shell.
2. In this project directory `npm install --build-from-source`

From Git bash
1. From this directory run `node_modules/bin/gulp.js start`

I got mine working!!!!

**Comment by shaielc** [comment]
@andrewjaykeller 

Hi had an error installing the hub on windows 10.

those steps did help with the installation

i ran:
 
```
PowerShell
npm install --global --production windows-build-tools
npm install --build-from-source
npm start
```

can you add this in the readme?

**Comment by daniellasry** [comment]
@shaielc Added! https://github.com/OpenBCI/OpenBCI_Hub/pull/83
