### ISSUE TITLE
A javascript error occured in the main process

### ISSUE THREAD

**Issue by aanexplus** [OpenBCI/OpenBCI_Hub#49]
I got this error while running "npm install"... Uncaught Exception: Error Could not locate the bindings file. Tried...

How can I resolve this issue?

**Comment by shirleyzhang867** [comment]
is this in windows?

**Comment by aanexplus** [comment]
Yes, on windows

Sent from Yahoo Mail on Android 
 
  On Wed, Apr 25, 2018 at 1:40 PM, shirleyzhang867<notifications@github.com> wrote:   
is this in windows?
