### ISSUE TITLE
Hub debug

### ISSUE THREAD

**Issue by ANDRO90** [OpenBCI/OpenBCI_Hub#58]
What's the best way to debug the OpenBCI_Hub? What IDE do I have to use?

I'm new to nodejs programming and since the structure of the Hub project is more complicated than the dummy introductory ones on the web, I cannot find a way to debug the application.
I tried some classic methods with **Visual Studio Code** but either they don't work at all or the debugger gets stuck in an asynchronous task and never reaches the printing 'app is ready'.

It is therefore much easier to ask to the experienced people that have developed the app so far. I'm sure there's an easy and straightforward way, but it seems I cannot find it :-)

Thanks for the support

**Comment by retiutut** [comment]
Use Visual Studio Code with NodeJS. Works fine on Mac, Windows, and Linux. You can even open two VSCode windows: one for OpenBCI GUI, the other from OpenBCI Hub. Launch the Hub first using `npm start`, then launch the GUI. If the Hub is already in the `data` folder, you may need to rename it temporarily.
