### ISSUE TITLE
CSR (Windows 10 or Linux): "Failed to start Ganglion BLE..." / "Code 412 Error: TypeError..."

### ISSUE THREAD

**Issue by wjcroft** [OpenBCI/OpenBCI_Hub#59]
See this forum thread:

http://openbci.com/forum/index.php?p=/discussion/1602/csr-windows-10-or-linux-failed-to-start-ganglion-ble-code-412-error-typeerror

The messages are either:

"Failed to start Ganglion BLE Driver"

or

"Code 412 Error: TypeError : Cannot read property 'state' of undefined"

FIVE different users have seen the first message. TWO different users are seeing the second message. A couple users in that thread managed to eventually get something working; one of those noticed that he could succeed with an older Hub version, but not the latest.

**Comment by wjcroft** [comment]
Would the BLED112 support be a possible long term solution to these Windows and Linux users having difficulties? The Zadig approach seems to be hitting snags.

**Comment by Fairview10071** [comment]
I get the "code 412 error" after first click on the CSR Dongle button, and the "Failed to start..." on subsequent clicks. Windows 10, build 1803.
 Apparently MS upgraded the bluetooth stack to version 5.0 with this build, but I have the same problem with build 1709. I have tested with CSR8510 A10 and BCM20702A0 dongles. I have ordered a BLED112.

For what its worth I can connect to the Ganglion board using a usb serial adapter and also with android phone running BLE apps, but my wifi shield claims it cannot see the ganglion board.

**Comment by andrewjaykeller** [comment]
I agree the zadig appears to be hitting snags. I think using the built in bluetooth and BLED112 should be idea. Older univerisities can still use a CSR but they just need to plug and play and ditch the whole zadig thing alltogether.

**Comment by wjcroft** [comment]
See the original forum thread. Some users report specific older Hub versions are working.
