### ISSUE TITLE
Searching for WiFi shield doesn't work on machines with multiple network interfaces

### ISSUE THREAD

**Issue by dyfer** [OpenBCI/OpenBCI_Hub#60]
When searching using service discovery, the HUB doesn't find WiFi shields connected to a secondary network interface. Tested with OpenBCI_GUI app version 3.3.2.

In this scenario connecting to the shield by IP still works fine, only searching doesn't.

I [reported similar issue for the Python library](https://github.com/OpenBCI/OpenBCI_Python/issues/83) as well, linking to the fix. The fix involved explicitly broadcasting multicast messages on all network interfaces. Not sure how to fix this here.

**Comment by retiutut** [comment]
I encountered this issue on Windows machine with a virtual box. A fix was implemented to look for "Ethernet" or "WiFi" network interface and use that.
