### ISSUE TITLE
Brainbay on Windows 10 doesn't work with BLED112 Bluetooth module

### ISSUE THREAD

**Issue by sebastiangula** [OpenBCI/OpenBCI_Hub#62]
After running BrainBay I click on Insert Element/Biosignal EEG Amplifier/OpenBCI Ganglion then OpenBCI Hub runs and I get the following error:

> No compatible USB Bluetooth 4.0 device found!

I suppose it is looking for CSR module by default, it should be possible to override this behaviour.
I am using OpenBCI Ganglion, which is working correctly with the OpenBCI GUI application.

**Comment by andrewjaykeller** [comment]
Hmm I wonder how we get brainbay to support this.

**Comment by wjcroft** [comment]
Wow, sorry for the long time lapse on this. I just notified @ChrisVeigl by opening an issue on his repo,

https://github.com/ChrisVeigl/BrainBay/issues/16

**Comment by wjcroft** [comment]
This issue should be closed, fixed by Chris in BrainBay, in late April.  @retiutut
